# Ignoring Paths
# --------------
# which folders/files to ignore
fixes:
  - "src/number_counter/::"

ignore:
  - "*/**/test/*"  # ignore package test directories
  - "*/test/**/*" # ignore package  test directories
  - "**/test_*.*" # ignore files starting with test_ 
  - "**/*_tests.*" # ignore files ending with _tests