name: CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: 
      image: docker.pkg.github.com/ximenesfel/ros1_python_dev_github_actions/docker:1.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}
    steps:
      - uses: actions/checkout@v2

      - name: Build code
        run: |
          mkdir ~/app
          cd ~/app
          mkdir -p ~/app/catkin_ws/src
          cd ~/app/catkin_ws/src
          cp -r $GITHUB_WORKSPACE .
          cd ~/app/catkin_ws/src/ros1_python_dev_github_actions
          cp -r * ..
          cd ~/app/catkin_ws/src/
          rm -r ros1_python_dev_github_actions
          cd ~/app/catkin_ws/
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make roslint_number_counter"
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make run_tests_number_counter -DENABLE_COVERAGE_TESTING=ON"

      - name: Run code coverage
        run: |
          mkdir -p ~/coverage
          cp ~/.ros/.coverage* ~/coverage
          cd ~/coverage
          python-coverage combine
          python-coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ~/coverage