name: CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      - uses: actions/checkout@v1
      - name: Install catkin & package dependencies
        run: |
          cd / && ./ros_entrypoint.sh
          apt-get update
          apt-get install -y ros-melodic-rospy-tutorials curl lcov python-coverage python-pip ros-melodic-genpy ros-melodic-code-coverage ros-melodic-roslint
          pip install --upgrade pip
          pip install pyyaml rospkg --ignore-installed

      - name: Setup catkin workspace
        run: |
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make"

      - name: Build package and run unit test
        run: |
          cd ~/catkin_ws/src
          cp -r $GITHUB_WORKSPACE .
          cd ~/catkin_ws
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make roslint_number_counter"
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make run_tests_number_counter -DENABLE_COVERAGE_TESTING=ON"
          mkdir -p ~/coverage
          cp ~/.ros/.coverage* ~/coverage
          cd ~/coverage
          python-coverage combine
          python-coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ~/coverage